@startuml Technical context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

System_Boundary(ftcloud,"FT Cloud") {
    System(vaco,"VACO")
    System(ura,"RAE")
    System(peti,"PETI")
    System(aggdb,"Aggregate \ndatabase")
    System_Ext(finap,"Finap")
}

System_Boundary(azure,"Azure") {
    System_Ext(auth_entraid,"Entra ID")
    System_Ext(auth_msgraph,"MS Graph")
}
System_Boundary(trivore,"Trivore") {
    System_Ext(auth_trivoreid,"Trivore ID")
}

System_Boundary(pta_sys,"PTA/TSP/Mobility operator") {
    System_Ext(psystem,"Planning \nsystem")
}

Rel(vaco,auth_entraid,"User Authentication", "on demand")
Rel(ura,auth_entraid,"User Authentication", "on demand")
Rel(peti,auth_trivoreid,"User Authentication and Authorization", "on demand")

Rel(ura,vaco,"User Authorization", "on demand")
Rel(vaco,auth_msgraph,"User Authorization", "on demand")

BiRel(auth_trivoreid,auth_entraid,"Data source", "metadadata")
BiRel(auth_trivoreid,auth_msgraph,"Data source", "metadadata")

Rel(finap,vaco,"Validate \nand \nconvert", "batch")

Rel(vaco,aggdb,"Publish results", "WebSocket push")

Rel(psystem,finap,"Publish open\ncatalog data")

SHOW_LEGEND()
@enduml
