@startuml AWS
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


System_Boundary(aws, "Amazon Web Services") {
    System_Ext(sqs, "Simple Queue Service") {
        Container_Ext(sqs_vaco_jobs,"VACO job delegator")
        Container_Ext(sqs_vaco_jobs_validation,"VACO validation jobs")
        Container_Ext(sqs_vaco_jobs_conversion,"VACO conversion jobs")
        Container_Ext(sqs_vaco_errors,"VACO errors ingest")
        Container_Ext(rules_results,"Rule results ingest")
        Container_Ext(rules_processing_per_rule,"Per-rule processing input")
    }
    System_Ext(s3, "Simple Storage Service") {
        Container_Ext(s3_processing,"digitraffic-tis-processing-{env}")
        Container_Ext(s3_packages,"digitraffic-tis-packages-{env}")
    }
}

SHOW_LEGEND()
@enduml
