@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Component Diagram for Job Delegator

LAYOUT_TOP_DOWN()

Component(job_delegator, "JobDelegator", "Java", "Reads in processing job notifications and redelegates them accordingly to matching processing queues")

System_Ext(sqs_jobs, "vaco_jobs", "AWS SQS topic")

System_Ext(sqs_validation, "vaco_jobs_validation", "AWS SQS topic")

System_Ext(sqs_conversion, "vaco_jobs_conversion", "AWS SQS topic")

System_Ext(validation, "Validation", "description")
System_Ext(conversion, "Conversion", "description")

Rel(sqs_jobs, job_delegator, "receives jobs", "JSON")
Rel(sqs_validation, job_delegator, "receives jobs", "JSON")
Rel(sqs_conversion, job_delegator, "receives jobs", "JSON")

Rel(job_delegator, sqs_conversion, "conversion jobs", "JSON")
Rel(job_delegator, sqs_validation, "validation jobs", "JSON")

Rel_D(sqs_validation, validation, "validation jobs", "JSON")
Rel_D(sqs_conversion, conversion, "conversion jobs", "JSON")

Lay_U(conversion, job_delegator)

SHOW_LEGEND()
@enduml
