@startuml
'https://plantuml.com/sequence-diagram
!theme fintraffic_c4 from ../layout

autonumber

queue  VacoJobs as "VACO Jobs / Validation"
control QueueListener
control Validation
participant DownloadFile

VacoJobs -> QueueListener: next queue entry
QueueListener -> Validation: entry and job metadata
Validation -> DownloadFile: download related file(s)
Validation <-- DownloadFile: file references

participant SelectRuleSets
database RulesetsDB
Validation -> SelectRuleSets: queue entry details
SelectRuleSets -> RulesetsDB: business id from entry
SelectRuleSets <-- RulesetsDB: rules to apply
Validation <-- SelectRuleSets: validation rules

Validation -> ExecuteRules: metadata, file references, validation rules

!includesub processing/rule_execution.puml!core

Validation <-- ExecuteRules: validation results
QueueListener <-- Validation: validation results

VacoJobs <-- QueueListener: acknowledge entry

@enduml
