@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!startsub core
Container_Boundary(cb_errorhandling, "Error Handling") {
    Component(c_errorlogger,"Error logging and reporting","Java", "Receives error and status messages, saves them into database and provides status information to the queue handler.")
    ComponentDb(log,"Log","Postgres")
}
ComponentQueue_Ext(cq_vaco_errors, "vaco-errors", "AWS SQS", "VACO errors ingest")
Rel(cq_vaco_errors, c_errorlogger, "Triggers error reporting")
BiRel(c_errorlogger,log,"Uses and updates","JDBC")
!endsub

SHOW_LEGEND()
@enduml
