@startuml
!theme fintraffic_c4 from ../../layout
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!startsub core
Container_Boundary(cb_jobdelegator, "Job Delegation") {
    Component(job_delegator, "JobDelegator", "Java", "Reads in processing job messages and redelegates them accordingly to matching processing queues")
}

ComponentQueue_Ext(cq_vaco_jobs, "vaco-jobs", "AWS SQS", "VACO job delegation queue")
ComponentQueue_Ext(cq_vaco_validation, "vaco-jobs-validation", "AWS SQS", "VACO validation jobs queue")
ComponentQueue_Ext(cq_vaco_conversion, "vaco-jobs-conversion", "AWS SQS", "VACO conversion jobs queue")

Rel_D(cq_vaco_jobs, job_delegator, "receives jobs", "JSON")
Rel_U(cq_vaco_validation, cq_vaco_jobs, "resubmit jobs", "JSON")
Rel_U(cq_vaco_conversion, cq_vaco_jobs, "resubmit jobs", "JSON")

Rel(job_delegator, cq_vaco_conversion, "conversion jobs", "JSON")
Rel(job_delegator, cq_vaco_validation, "validation jobs", "JSON")

!endsub

SHOW_LEGEND()
@enduml
