name: Release new version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout project files
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract next version
        run: echo VERSION_STRING=$(git rev-list --count HEAD) >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.VERSION_STRING }}",
              sha: context.sha
            })
