name: Release new version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout project files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if Actor is a Member of one of the teams
        uses: im-open/is-actor-team-member@v1.2.0
        with:
          github-actor: ${{ github.actor }}
          github-organization: tmfg
          github-team-slugs: |
            ["digitraffic-tis-solita"]
          github-usernames: |
            ["dependabot[bot]"]
          github-token: ${{ secrets.ORG_MEMBER_READ }}

      - name: Extract next version
        run: echo VERSION_STRING=$(git rev-list --count HEAD) >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ env.VERSION_STRING }}",
              sha: context.sha
            })
